---
title: "descriptive table"
author: "bf2506"
date: "2023-05-07"
output: pdf_document
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(caret)
library(summarytools)
```

## 1. Load Data
```{r message=FALSE, warning=FALSE}
load("final_data.RData")
final_data = final_data %>% 
  mutate(binary_recovery_time = as.factor(binary_recovery_time))
levels(final_data$binary_recovery_time) = c("low", "high")
```

## 2. Train/test split
```{r message=FALSE, warning=FALSE}
set.seed(2)
training_rows <- createDataPartition(final_data$binary_recovery_time,
                                     p = 0.8,
                                     list = F)
```

```{r message=FALSE, warning=FALSE}
training_set <- final_data[training_rows,]
```

```{r message=FALSE, warning=FALSE, results = 'asis'}
st_options(plain.ascii = FALSE, 
           style = "rmarkdown", 
           dfSummary.silent = TRUE,
           footnote = NA, 
           subtitle.emphasis = FALSE)






dfSummary(training_set[,-1])
```

